# Example of PostgreSQL cluster
# https://cloudnative-pg.io/documentation/1.20/cloudnative-pg.v1/
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-example
spec:
  instances: 3

  # Example of rolling update strategy:
  # - unsupervised: automated update of the primary once all
  #                 replicas have been upgraded (default)
  # - supervised: requires manual supervision to perform
  #               the switchover of the primary
  primaryUpdateStrategy: unsupervised

  # Require 2Gi of space
  storage:
    size: 2Gi